create SCHEMA  TESTDB;

CREATE TABLE serv_disc
(
  NAME VARCHAR(50) PRIMARY KEY NOT NULL,
  VAL VARCHAR(255) NOT NULL,
  LAST_UPDATED DATETIME NOT NULL,
  TYPE VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX SERV_DISC_NAME_uindex ON serv_disc (NAME);